### ISSUE TITLE
Array Index Out of Bounds

### ISSUE THREAD

**Issue by andrewjmc** [Nesvilab/Crystal-C#1]
Hello,

I have been using MSFragger/FragPipe to good effect. However, in a larger protein database (human + custom antibody database) I have encountered a CrystalC error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
        at MSProcessor.p_WriteResults.WritePepXML(p_WriteResults.java:237)
        at Main.ProcessPepXML(Main.java:132)
        at Main.main(Main.java:72)
```

It occurs on both a Linux and Windows machine.

I'd be grateful for any advice, and can share files as needed.

Best wishes,

Andrew

**Comment by huiyinc** [comment]
Hi Andrew,
Are you running open search via FragPipe?!
And, for the protein headers (e.g., >sp|O94903|PLPHP_HUMAN .....) in your custom antibody database, could you please give me an example of how you define the protein headers?!
Thanks.

Huiyin

**Comment by andrewjmc** [comment]
Yes, this is the open search via FragPipe... however, I had to manually run the crystalC step on the linux box since java complained it couldn't find the "Main class" -- I suspect this has something to do with not finding an appropriate temporary storage location for the crystalC jar.

So instead, I extracted the crystalC and common-deps jars and ran the command myself (this has worked fine for previous database searches).

```
java -Xmx16G -cp "/nnn/common-deps-1.0.3.jar:/nnn/original-CrystalC-1.0.4.jar" Main crystalc.params a.pepXML
```

The protein headers would be a likely candidate. The database is two fasta files concantenated, with reversed decoys. The first is a UniProt human database with identifiers like: 
```
>sp|A0A1W2PR19.1|GSTT4_HUMAN RecName: Full=Glutathione S-transferase theta-4; AltName: Full=GST class-theta-4; AltName: Full=Glutathione S-transferase theta pseudogene 1
```
The second is a series of human antibody sequences from a research database that has been kindly shared with me. I have given each a name comprising a consecutive number, and the freetext name in the database. This does result in some unusual names, and I already had to XML escape <>"& to ensure it worked.

For example:
```
>1_I-3b'CL_1
>2_E3-10'CL_1
>3_I-3'CL_1
>4_1-92'CL_1
...
>578_Au4.1'CL_1
>579_HuRSV19VHFNS_1
```

Are there any characters or patterns in sequence names that might cause crystalC a problem?

Many thanks for your help,

Andrew

**Comment by huiyinc** [comment]
Hi Andrew,

It is possible because the headers for the antibody sequences doesn't follow the header format of human proteins. Crystal-C expects the header format as:
>sp|A0A1W2PR19.1|GSTT4_HUMAN RecName:....., where a white space is between ">sp|A0A1W2PR19.1|GSTT4_HUMAN" and "RecName:.....".

I can take a look of the issue if you could share me the fasta, raw file (mzML/mzXML), and pepXML file.
Thanks.

Huiyin

**Comment by andrewjmc** [comment]
That sounds promising. What is the best way to share sizable files?

In the meantime, I can change my antibody headers to match. How specific do they need to be? Is it just that they need at least one space? Or do they expect the sp|A|B format with a RecName: entry?

Thanks,

Andrew

**Comment by huiyinc** [comment]
You could use Box to share the file if you have an account.
And, it's good if I can take a look the files to make sure the issue is due to the header format.
Thanks. :)

Huiyin

**Comment by andrewjmc** [comment]
I have shared a folder with you containing a fasta target-decoy database, mzXML and pepXML files.

Thanks for all your help,

Andrew

**Comment by andrewjmc** [comment]
Strangely... today I tried again (from the command line, since I still get the Main class error from FragPipe - separate issue raised) and found that CrystalC ran fine.

It is probably entirely my fault, as I may have used a hand-spun crystalC config by mistake -- perhaps the most likely error is that it did not correctly point to the sequence database (as I used a relative path).

I'm sorry for wasting your time!

Best wishes,

Andrew

**Comment by andrewjmc** [comment]
Sorry, my mistake again. I must have accidentally left it pointing at the UniProt database. Once I re-ran it ensuring it pointed to my combined database, same error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
        at MSProcessor.p_WriteResults.WritePepXML(p_WriteResults.java:237)
        at Main.ProcessPepXML(Main.java:132)
        at Main.main(Main.java:72)
```

So I'm sure you're right about naming conventions.

Best wishes,

Andrew

**Comment by huiyinc** [comment]
Hi Andrew,

After checking the fasta and pepXML files, I notice that there is a strange string in the protein header (e.g., &amp;amp;quot;). This is the reason why Crystal-C pops up the error message because it can't recognize the header correctly.
Could you please replace "&amp;amp;quot;" with " " (a white space, as other human protein header)?! 
Please make sure the protein accessions in the pepXML file are also replaced so that they can be consistent with those in the fasta file.

Please feel free to let me know if you have other questions.
Thanks.

Huiyin

**Comment by andrewjmc** [comment]
Thanks very much Huiyin. Indeed it all worked when I dropped this.

I tried to preserve the full descriptions of the original proteins, but had to make them xml escaped, hence the &amp; etc.

As it happens, since I have given them all unique identifiers, the lack of full descriptors is not critical.

Many thanks for your help,

Andrew

**Comment by huiyinc** [comment]
Hi Andrew,

No problem!
Please feel free to ask if you have other questions.
Have a good day.

Huiyin
